server:
  port: 8082

spring:
  application:
    name: drive-service
  datasource:
    url: jdbc:mysql://localhost:3308/recruitr_drive_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

gemini:
  api-key: ${GEMINI_API_KEY}
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent"
